DEF VAR cProg AS CHAR NO-UNDO.
DEF VAR cMessage AS CHAR NO-UNDO.
DEF VAR i AS INT NO-UNDO.

cProg = ENTRY(1, SESSION:PARAM).

COMPILE VALUE(cProg) SAVE=NO NO-ERROR.

IF COMPILER:NUM-MESSAGES > 0 THEN
  DO i = 1 TO COMPILER:NUM-MESSAGES:
    cMessage = SUBSTITUTE(
      "&1:&2:&3:&4 &5",
      COMPILER:GET-FILE-NAME(i),
      COMPILER:GET-ROW(i),
      COMPILER:GET-COLUMN(i),
      IF COMPILER:GET-MESSAGE-TYPE(i) = 1 THEN "E" ELSE "W",
      COMPILER:GET-MESSAGE(i)
    ).

    PUT UNFORMATTED cMessage SKIP.
  END.
